org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.21.11
loader_version=0.18.1
loom_version=1.14-SNAPSHOT

mod_version=1.0.0
maven_group=com.kitmod
archives_base_name=kitmod

fabric_version=0.141.4+1.21.11
